spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000

jwt:
  token:
    secretKey: ${JWT_SECRET}
    expiration:
      access: ${JWT_ACCESS_TOKEN_VALIDITY_IN_MILLISECONDS}

keys:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    places:
      key: ${GOOGLE_PLACES_API_KEY}
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    client-secret: ${KAKAO_CLIENT_SECRET}


cloud:
  aws:
    s3:
      bucket: umc-8th
      path:
        review: review
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
